drop table KhachHang cascade constraints ;
drop table KhachHangNL cascade constraints;
drop table KhachHangTE cascade constraints;
drop table TrangThaiTG cascade constraints;
drop table PhiVCHH cascade constraints;
drop table ChuyenBay cascade constraints;
drop table GheKhach cascade constraints;
drop table MayBay cascade constraints;
drop table LoaiMayBay cascade constraints;
drop table GheNgoi cascade constraints;
drop table TuyenBay cascade constraints;
drop table Ga cascade constraints;
drop table ThucPham cascade constraints;
drop table ChuyenBay cascade constraints;
drop table NhanVien cascade constraints;
drop table BangCap cascade constraints;
drop table PhiCong cascade constraints;
drop table TiepVien cascade constraints;
drop table ChiNhanh cascade constraints;
drop table CaLamViec cascade constraints;
drop table NhanVienMD cascade constraints;
drop table NVMatDat_CaLV cascade constraints;
drop table VanHanh cascade constraints;
drop table Lai cascade constraints;
drop table KiemTra cascade constraints;
drop table ChuyenMonBD cascade constraints;
drop table ChuyenBayThucPham cascade constraints;
drop table GiaThucPham cascade constraints;
drop sequence KhachHang_MSKH_NL_SQ;
drop sequence KhachHang_MSKH_TE_SQ;
drop sequence PhiVCHH_SEQ;
drop sequence TrangThai_SEQ;